"""Constants mapping the physical DMX channels to logical divisions of the
sign.
"""

###########################################################
# Single (Atomic) Channels
###########################################################

# Logo
CHS_ATOM_LOGO_STEM_LEFT = {3}
CHS_ATOM_LOGO_GERMS_LEFT = {5}
CHS_ATOM_LOGO_STEM_RIGHT_AND_TOP_GERMS = {7}
CHS_ATOM_LOGO_GERMS_RIGHT = {9}

# "Tell"
CHS_ATOM_LETTER_T1 = {11}
CHS_ATOM_LETTER_E1_INSIDE = {13}
CHS_ATOM_LETTER_E1_OUTSIDE = {15}
CHS_ATOM_LETTER_L1 = {17}
CHS_ATOM_LETTER_L2 = {21}

# "Apart"
CHS_ATOM_LETTER_A1_LEFT_STEM = {23}
CHS_ATOM_LETTER_A1_RIGHT = {19}
CHS_ATOM_LETTER_P1_INSIDE = {27}
CHS_ATOM_LETTER_P1_OUTSIDE = {25}
CHS_ATOM_LETTER_A2_INSIDE = {31}
CHS_ATOM_LETTER_A2_OUTSIDE = {29}
CHS_ATOM_LETTER_R1 = {35}
CHS_ATOM_LETTER_T2 = {33}

###########################################################
# Logical Compounds
###########################################################

# Logo
CHS_LOGO = (
  CHS_ATOM_LOGO_STEM_LEFT |
  CHS_ATOM_LOGO_GERMS_LEFT |
  CHS_ATOM_LOGO_STEM_RIGHT_AND_TOP_GERMS |
  CHS_ATOM_LOGO_GERMS_RIGHT)

# Letters
CHS_LETTER_T1 = CHS_ATOM_LETTER_T1
CHS_LETTER_E1 = CHS_ATOM_LETTER_E1_INSIDE | CHS_ATOM_LETTER_E1_OUTSIDE
CHS_LETTER_L1 = CHS_ATOM_LETTER_L1
CHS_LETTER_L2 = CHS_ATOM_LETTER_L2

CHS_LETTER_A1 = CHS_ATOM_LETTER_A1_LEFT_STEM | CHS_ATOM_LETTER_A1_RIGHT
CHS_LETTER_P1 = CHS_ATOM_LETTER_P1_INSIDE | CHS_ATOM_LETTER_P1_OUTSIDE
CHS_LETTER_A2 = CHS_ATOM_LETTER_A2_INSIDE | CHS_ATOM_LETTER_A2_OUTSIDE
CHS_LETTER_R1 = CHS_ATOM_LETTER_R1
CHS_LETTER_T2 = CHS_ATOM_LETTER_T2

# Words
CHS_TELL = (
  CHS_LETTER_T1 |
  CHS_LETTER_E1 |
  CHS_LETTER_L1 |
  CHS_LETTER_L2)

CHS_APART = (
  CHS_LETTER_A1 |
  CHS_LETTER_P1 |
  CHS_LETTER_A2 |
  CHS_LETTER_R1 |
  CHS_LETTER_T2)

CHS_TELLAPART = CHS_TELL | CHS_APART

# Everything
CHS_ALL = CHS_LOGO | CHS_TELLAPART

CHS_ALL_ALL = set(range(max(CHS_ALL)))

NUM_CHANNELS = max(CHS_ALL)

